--1 Depende de un ID persona
SELECT *
FROM CLIENTE
--con nombre completo y un contacto
SELECT CLIENTE.IDCLIENTE, PERSONA.NOMBRE+' '+PERSONA.APELLIDO AS NOMBRE, CLIENTE.TIPOCLIENTE,CLIENTE.CODIGOCLIENTE,PERSONA.TELEFONO,CLIENTE.ESTADO
FROM CLIENTE 
INNER JOIN PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA

--2 DEPENDE DE UN ID INGRESO Y ID PRODUCTO
SELECT *
FROM DETALLEING
--NOMBRE PRODUCTO FECHA INGRESO
SELECT DETALLEING.IDDETALLEING, PRODUCTO.NOMBRE, INGRESO.FECHAINGRESO,DETALLEING.FECHAVENC, DETALLEING.CANTIDAD, 
		DETALLEING.PRECIOCOSTO, DETALLEING.PRECIOVENTA, DETALLEING.SUBTOTAL, DETALLEING.ESTADO
FROM DETALLEING 
INNER JOIN INGRESO ON DETALLEING.IDINGRESO = INGRESO.IDINGRESO 
INNER JOIN PRODUCTO ON DETALLEING.IDPRODUCTO = PRODUCTO.IDPRODUCTO

--3 DEPENDE DE UN ID VENTA Y ID PRODUCTO
SELECT *
FROM DETALLEVENTA
--fecha venta nombre producto
SELECT DETALLEVENTA.IDDETALLEVENTA, VENTA.FECHA, PRODUCTO.NOMBRE, 
		DETALLEVENTA.CANTIDAD,DETALLEVENTA.PRECIOVENTA, DETALLEVENTA.SUBTOTAL, DETALLEVENTA.ESTADO
FROM DETALLEVENTA 
INNER JOIN VENTA ON DETALLEVENTA.IDVENTA = VENTA.IDVENTA 
INNER JOIN PRODUCTO ON DETALLEVENTA.IDPRODUCTO = PRODUCTO.IDPRODUCTO

--4 DEPENDE DE UN ID PROVEEDOR
SELECT *
FROM INGRESO
--nombre, telefono y direccion proveedor
SELECT I.IDINGRESO, P.NOMBRE AS NOM_PROVEEDOR, P.DIRECCION, P.TELEFONO, I.FECHAINGRESO, I.TOTAL, I.ESTADO
FROM INGRESO I
INNER JOIN PROVEEDOR P ON P.IDPROVEEDOR = I.IDPROVEEDOR
--5 INDEPENDIENTE
SELECT *
FROM MARCA
--nombre y descripcion de producto
SELECT M.IDMARCA, M.NOMBRE AS NOMBRE_PROD, P.DESCRIPCION, M.ESTADO
FROM MARCA M
INNER JOIN PRODUCTO P ON P.IDMARCA = M.IDMARCA


--6 INDEPENDIENTE
SELECT *
FROM PERSONA
--nombre completo, fecha y nombre de usuario
SELECT P.IDPERSONA, P.NOMBRE+' '+P.APELLIDO AS NOMBRE,U.NOMBREUSER, U.FECHAREG, 
P.TELEFONO, P.CI, P.CORREO,P.ESTADO
FROM PERSONA P
INNER JOIN USUARIO U ON U.IDPERSONA = P.IDPERSONA

--7 DEPENDE DE UN ID MARCA Y ID TIPO PRODUCTO
SELECT *
FROM PRODUCTO
--nombre de tipo prod y marca,
SELECT P.IDPRODUCTO, TP.NOMBRE AS TIPOPRODUCTO, M.NOMBRE AS MARCA, 
P.NOMBRE, P.CODIGOBARRA,P.UNIDAD,P.DESCRIPCION,P.ESTADO
FROM PRODUCTO P 
INNER JOIN TIPOPROD TP ON TP.IDTIPOPROD = P.IDTIPOPROD
INNER JOIN MARCA M ON M.IDMARCA = P.IDMARCA

--8 DEPENDE DE UN ID PROVEEDOR
SELECT *
FROM PROVEE
--nombre de proveedor y producto, telefono proveedor
SELECT PEE.IDPROVEE, P.NOMBRE AS PRODUCTO,
PEER.NOMBRE AS PROVEEDOR, PEE.FECHA,PEE.PRECIO
FROM PROVEE PEE
INNER JOIN PRODUCTO P ON P.IDPRODUCTO = PEE.IDPRODUCTO
INNER JOIN PROVEEDOR PEER ON PEE.IDPROVEEDOR = PEER.IDPROVEEDOR
--9 INDEPENDIENTE
SELECT *
FROM PROVEEDOR
--producto nombre precio
SELECT PEER.IDPROVEEDOR, PEER.NOMBRE,P.NOMBRE AS PRODUCTO,
PEE.PRECIO,PEER.TELEFONO,PEER.DIRECCION,PEER.ESTADO
FROM PROVEEDOR PEER
INNER JOIN PROVEE PEE ON PEE.IDPROVEEDOR= PEER.IDPROVEEDOR
INNER JOIN PRODUCTO P ON P.IDPRODUCTO=PEE.IDPRODUCTO

--10 INDEPENDIENTE
SELECT *
FROM ROL
--fecha asig, nombre user
SELECT R.IDROL, U.NOMBREUSER AS USUARIO, R.NOMBRE AS ROL, UR.FECHAASIGNA, R.ESTADO
FROM ROL R
INNER JOIN USUARIOROL UR ON R.IDROL=UR.IDROL
INNER JOIN USUARIO U ON U.IDUSUARIO = UR.IDUSUARIO
----11 INDEPENDIENTE
SELECT *
FROM TIPOPROD
--nombre producto descripcion y unidad
SELECT TP.IDTIPOPROD, P.NOMBRE AS PRODUCTO, P.DESCRIPCION,P.UNIDAD,TP.ESTADO
FROM TIPOPROD TP
INNER JOIN PRODUCTO P ON P.IDTIPOPROD = TP.IDTIPOPROD

--12 INDEPENDIENTE
SELECT *
FROM USUARIO
--nombre completo de persona, rol y fecha
SELECT U.IDUSUARIO,P.NOMBRE +' '+P.APELLIDO AS NOMBRE, U.NOMBREUSER,
R.NOMBRE AS ROL, U.CONTRASEÑA, U.FECHAREG
FROM USUARIO U
INNER JOIN PERSONA P ON P.IDPERSONA = U.IDPERSONA
INNER JOIN USUARIOROL UR ON UR.IDUSUARIO = U.IDUSUARIO
INNER JOIN ROL R ON R.IDROL = UR.IDROL

--13 DEPENDE DE ID ROL
SELECT *
FROM USUARIOROL
-- nombre user y rol
SELECT UR.IDUSUARIOROL, U.NOMBREUSER, R.NOMBRE AS ROL,
UR.FECHAASIGNA, UR.ESTADO
FROM USUARIOROL UR
INNER JOIN USUARIO U ON U.IDUSUARIO = UR.IDUSUARIO
INNER JOIN ROL R ON R.IDROL = UR.IDROL

--14 DEPENDE DE UN ID CLIENTE Y ID VENDEDOR
SELECT *
FROM VENTA
--nombre cliente, nombre vendedor de usuario
SELECT VENTA.IDVENTA, VENTA.FECHA, VENTA.TOTAL, VENTA.ESTADO, CLIENTE.IDCLIENTE, PERSONA.IDPERSONA, PERSONA.NOMBRE, PERSONA.APELLIDO, VENTA.IDVENDEDOR
FROM CLIENTE 
INNER JOIN PERSONA ON CLIENTE.IDPERSONA = PERSONA.IDPERSONA 
INNER JOIN USUARIO ON PERSONA.IDPERSONA = USUARIO.IDPERSONA 
INNER JOIN USUARIOROL ON USUARIO.IDUSUARIO = USUARIOROL.IDUSUARIO 
INNER JOIN ROL ON USUARIOROL.IDROL = ROL.IDROL 
INNER JOIN VENTA ON CLIENTE.IDCLIENTE = VENTA.IDCLIENTE AND USUARIO.IDUSUARIO = VENTA.IDVENDEDOR



SELECT V.IDVENTA, P.NOMBRE +' '+P.APELLIDO AS NOMBRE_CLIENTE,
V.IDVENDEDOR, V.FECHA, V.TOTAL, V.ESTADO
FROM VENTA V
INNER JOIN CLIENTE C ON C.IDCLIENTE = V.IDCLIENTE
INNER JOIN PERSONA P ON P.IDPERSONA = C.IDPERSONA
INNER JOIN USUARIO U ON U.IDPERSONA = P.IDPERSONA

