--1.Encuentra el nombre y apellido de todos los clientes.
SELECT C.IDCLIENTE, P.NOMBRE + ' ' + P.APELLIDO AS NOMBRES
FROM CLIENTE C
INNER JOIN PERSONA P ON P.IDPERSONA = C.IDPERSONA
--2.Calcula el total de ingresos generados por cada proveedor.
SELECT PEER.IDPROVEEDOR, PEER.NOMBRE, SUM(I.TOTAL)TOTAL_ING
FROM PROVEEDOR PEER
INNER JOIN INGRESO I ON PEER.IDPROVEEDOR = I.IDPROVEEDOR
GROUP BY PEER.IDPROVEEDOR, PEER.NOMBRE 
--3.Encuentra el nombre de la marca más vendida.
SELECT TOP 1 M.IDMARCA, M.NOMBRE, SUM(V.TOTAL)TOTAL
FROM MARCA M
INNER JOIN PRODUCTO P ON P.IDMARCA = M.IDMARCA
INNER JOIN DETALLEVENTA DT ON P.IDPRODUCTO = DT.IDPRODUCTO
INNER JOIN VENTA V ON V.IDVENTA = DT.IDVENTA
GROUP BY M.IDMARCA, M.NOMBRE 
ORDER BY TOTAL DESC
--4.Obtén la cantidad total de productos en inventario.
SELECT ESTADO, SUM(UNIDAD)PROD_INVENTARIO
FROM PRODUCTO
GROUP BY ESTADO

--5.Encuentra los productos con fecha de vencimiento próximos a expirar.
SELECT P.IDPRODUCTO, P.NOMBRE, DG.FECHAVENC
FROM PRODUCTO P
INNER JOIN DETALLEING DG ON DG.IDPRODUCTO = P.IDPRODUCTO
WHERE YEAR(FECHAVENC) = 2024 AND MONTH(FECHAVENC)= 04


--6. Encuentra el nombre y la cantidad de productos vendidos por cada vendedor.
SELECT V.IDVENDEDOR, P.NOMBRE, DT.CANTIDAD
FROM VENTA V
INNER JOIN DETALLEVENTA DT ON DT.IDVENTA = V.IDVENTA
INNER JOIN PRODUCTO P ON P.IDPRODUCTO = DT.IDPRODUCTO
ORDER BY IDVENDEDOR

--7.Calcula el total de ingresos generados por cada cliente.
SELECT C.IDCLIENTE, SUM(I.TOTAL)INGRESO_TOTAL, C.ESTADO
FROM CLIENTE C
INNER JOIN VENTA V ON C.IDCLIENTE = V.IDCLIENTE
INNER JOIN DETALLEVENTA DT ON DT.IDVENTA = V.IDVENTA
INNER JOIN PRODUCTO P ON P.IDPRODUCTO = DT.IDPRODUCTO
INNER JOIN DETALLEING DG ON DG.IDPRODUCTO = P.IDPRODUCTO
INNER JOIN INGRESO I ON I.IDINGRESO = DG.IDINGRESO
GROUP BY C.IDCLIENTE, C.ESTADO
--8.Encuentra el nombre del proveedor que ha suministrado más productos.
SELECT TOP 1 PEER.IDPROVEEDOR, PEER.NOMBRE, SUM(DG.CANTIDAD)CANTIDAD_PRODUC
FROM PROVEEDOR PEER
INNER JOIN INGRESO I ON PEER.IDPROVEEDOR = I.IDPROVEEDOR
INNER JOIN DETALLEING DG ON I.IDINGRESO = DG.IDINGRESO
GROUP BY PEER.IDPROVEEDOR, PEER.NOMBRE
ORDER BY CANTIDAD_PRODUC DESC

--9.Obtén la cantidad total de productos vendidos por tipo de producto.
SELECT TP.IDTIPOPROD, TP.NOMBRE, SUM(DT.CANTIDAD)CANTIDAD
FROM PRODUCTO P 
INNER JOIN TIPOPROD TP ON TP.IDTIPOPROD = P.IDTIPOPROD
INNER JOIN DETALLEVENTA DT ON DT.IDPRODUCTO = P.IDPRODUCTO
GROUP BY TP.IDTIPOPROD, TP.NOMBRE
--10.Encuentra los clientes que hayan realizado compras por un monto superior a cierta cantidad especificada.
SELECT C.IDCLIENTE, V.TOTAL
FROM CLIENTE C
INNER JOIN VENTA V ON V.IDCLIENTE = C.IDCLIENTE
WHERE V.TOTAL >= 20.00
ORDER BY IDCLIENTE